language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: stable
script:
  - npm run lint
  - npm run codecov
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $CF_USERNAME
  password: $CF_PASSWORD
  name: conversation-simple
  organization: WatsonPlatformServices
  space: demos
  on:
    repo: watson-developer-cloud/conversation-simple
    branch: release
